sudo: true

dist: xenial

language: generic

cache: apt

addons:
  apt:
    packages:
        - texlive-full
        - asymptote
        - wget

install:
    - sudo wget -P /usr/share/texmf/tex/latex/ http://www.paultaylor.eu/diagrams/diagrams.sty
    - sudo texhash
    
script:
    - latexmk -halt-on-error -interaction=nonstopmode 
