 version: 2
 jobs:
   build:
     docker:
       - image: thomasweise/texlive 
     steps:
       - checkout
       - run: echo "A first hello"
       - run: latex.sh Napkin
       - run: latexmk -shell-escape -interaction=nonstopmode -halt-on-error
